# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/alcohol_killer/Desktop/app_version_3/ui files/app.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(620, 630)
        MainWindow.setMinimumSize(QtCore.QSize(620, 630))
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 30, 120, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(120, 20))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.base_update = QtWidgets.QRadioButton(self.centralwidget)
        self.base_update.setGeometry(QtCore.QRect(320, 250, 240, 30))
        self.base_update.setMinimumSize(QtCore.QSize(180, 30))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.base_update.setFont(font)
        self.base_update.setStyleSheet("color: rgb(0, 0, 0);\n"
"")
        self.base_update.setChecked(False)
        self.base_update.setObjectName("base_update")
        self.new_file = QtWidgets.QLineEdit(self.centralwidget)
        self.new_file.setGeometry(QtCore.QRect(60, 200, 400, 30))
        self.new_file.setStyleSheet("color: rgb(150, 150, 150);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: rgb(0, 206, 0);")
        self.new_file.setAlignment(QtCore.Qt.AlignCenter)
        self.new_file.setReadOnly(True)
        self.new_file.setObjectName("new_file")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(60, 290, 240, 180))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_2.sizePolicy().hasHeightForWidth())
        self.textBrowser_2.setSizePolicy(sizePolicy)
        self.textBrowser_2.setMinimumSize(QtCore.QSize(240, 160))
        self.textBrowser_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: rgb(0, 206, 0);")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.new_pictures = QtWidgets.QRadioButton(self.centralwidget)
        self.new_pictures.setGeometry(QtCore.QRect(60, 250, 240, 30))
        self.new_pictures.setMinimumSize(QtCore.QSize(180, 30))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.new_pictures.setFont(font)
        self.new_pictures.setStyleSheet("color: rgb(0, 0, 0);")
        self.new_pictures.setChecked(True)
        self.new_pictures.setObjectName("new_pictures")
        self.base = QtWidgets.QLineEdit(self.centralwidget)
        self.base.setGeometry(QtCore.QRect(60, 60, 400, 30))
        self.base.setStyleSheet("color: rgb(150, 150, 150);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: rgb(0, 206, 0);")
        self.base.setAlignment(QtCore.Qt.AlignCenter)
        self.base.setReadOnly(True)
        self.base.setObjectName("base")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(320, 290, 240, 180))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setMinimumSize(QtCore.QSize(240, 160))
        self.textBrowser.setStyleSheet("color: rgb(0, 0, 0);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: rgb(0, 206, 0);")
        self.textBrowser.setObjectName("textBrowser")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 100, 120, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(120, 20))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 170, 120, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(120, 20))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.img_base = QtWidgets.QLineEdit(self.centralwidget)
        self.img_base.setGeometry(QtCore.QRect(60, 130, 400, 30))
        self.img_base.setStyleSheet("color: rgb(150, 150, 150);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: rgb(0, 206, 0);")
        self.img_base.setAlignment(QtCore.Qt.AlignCenter)
        self.img_base.setReadOnly(True)
        self.img_base.setObjectName("img_base")
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setGeometry(QtCore.QRect(60, 500, 500, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_start.sizePolicy().hasHeightForWidth())
        self.btn_start.setSizePolicy(sizePolicy)
        self.btn_start.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.btn_start.setFont(font)
        self.btn_start.setStyleSheet("background-color: rgb(0, 206, 0);\n"
"")
        self.btn_start.setObjectName("btn_start")
        self.Browse1 = QtWidgets.QPushButton(self.centralwidget)
        self.Browse1.setGeometry(QtCore.QRect(480, 60, 80, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Browse1.sizePolicy().hasHeightForWidth())
        self.Browse1.setSizePolicy(sizePolicy)
        self.Browse1.setStyleSheet("color: rgb(0, 0, 0);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: rgb(0, 206, 0);")
        self.Browse1.setObjectName("Browse1")
        self.Browse2 = QtWidgets.QPushButton(self.centralwidget)
        self.Browse2.setGeometry(QtCore.QRect(480, 130, 80, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Browse2.sizePolicy().hasHeightForWidth())
        self.Browse2.setSizePolicy(sizePolicy)
        self.Browse2.setStyleSheet("color: rgb(0, 0, 0);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: rgb(0, 206, 0);")
        self.Browse2.setObjectName("Browse2")
        self.Browse3 = QtWidgets.QPushButton(self.centralwidget)
        self.Browse3.setGeometry(QtCore.QRect(480, 200, 80, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Browse3.sizePolicy().hasHeightForWidth())
        self.Browse3.setSizePolicy(sizePolicy)
        self.Browse3.setStyleSheet("color: rgb(0, 0, 0);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: rgb(0, 206, 0);\n"
"")
        self.Browse3.setObjectName("Browse3")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(60, 570, 500, 50))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "app version 4"))
        self.label.setText(_translate("MainWindow", "Բազա"))
        self.base_update.setText(_translate("MainWindow", "Բազայի Թարմացում"))
        self.new_file.setText(_translate("MainWindow", "֊ ֊ ֊  ընտրեք նոր ֆայլը  ֊ ֊ ֊"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Ընտրեք ապրանքների բազան,նկարների բազան, նոր ֆայլը որից ցանկանում եք ստանալ նոր նկարները և սեղմեք START կոճակին։ Այն ապրանքները որոնք առկա չեն բազայում կստանանք նոր Excel ֆայլով։</p></body></html>"))
        self.new_pictures.setText(_translate("MainWindow", "Նոր Նկարներ"))
        self.base.setText(_translate("MainWindow", "֊ ֊ -  ընտրեք ապրանքների բազան  ֊ ֊ ֊"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Ընտրեք բազան, նոր ֆայլը որով ցանկանում եք թարմացնել բազան։ Եթե տվյալ ապրանքը առկա է բազայում ապա կթարմացվի բազայում ապրանքի գինը։ Եթե տվյալ ապրանքը առկա չէ բազայում ապա այն կավելանա բազայում։ </p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "Նկարների բազա"))
        self.label_2.setText(_translate("MainWindow", "Նոր ֆայլ"))
        self.img_base.setText(_translate("MainWindow", "- ֊ ֊  ընտրեք նկարների բազան  ֊ ֊ ֊"))
        self.btn_start.setText(_translate("MainWindow", "START"))
        self.Browse1.setText(_translate("MainWindow", "Browse"))
        self.Browse2.setText(_translate("MainWindow", "Browse"))
        self.Browse3.setText(_translate("MainWindow", "Browse"))
